export const voices = [
    { name: "Heather - Mature British lady", id: "4XHqIi1c86s718fjqNEF" },
    { name: "Kate - older British voice", id: "JqqFyydyksim5yVVTgAK" },
    { name: "Aaron", id: "D9Thk1W7FRMgiOhy3zVI" },
    { name: "Aiden - The Everyday Guy", id: "4zVVKJJRwoOAAeUwtCQ1" },
    { name: "Amber", id: "2BP0mL5uSfNKL5oaqVC0" },
    { name: "Andrea", id: "qHkrJuifPpn95wK3rm2A" },
    { name: "Arabella", id: "Z3R5wn05IrDiVCyEkUrK" },
    { name: "Ash", id: "ug7mg45jVbzgYHpQBrw5" },
    { name: "Attank", id: "Z7HhYXzYeRsQk3RnXqiG" },
    { name: "Benji", id: "wWUG72eEtupiUkpXafwX" },
    { name: "Beyond Average Joe", id: "V5RKORVpYueDvTQHfALW" },
    { name: "Bob Eastman", id: "vRiW8gVSMIVJXaMhNy2V" },
    { name: "Brian", id: "2PvEwT8I49J7FpkMNz1M" },
    { name: "Brian Nguyen", id: "bP8FJDHmWVEgXJDitdQd" },
    { name: "Brian Overturf", id: "ryn3WBvkCsp4dPZksMIf" },
    { name: "Cecily - Professional", id: "t9IV45xnQb79w1JXFAIQ" },
    { name: "Chrissy - Millenial Female", id: "3eIAPRQVsX0VrSFmqoTf" },
    { name: "Crystal", id: "tRhabdS7JjlQ0lVEImuM" },
    { name: "Dakota H", id: "P7x743VjyZEOihNNygQ9" },
    { name: "Dez", id: "yHx9q5iHmtVGKONrqrIf" },
    { name: "Felicia", id: "H61ermx0gHYPgQYw03E4" },
    { name: "Giselle Marie", id: "XN5MUfNpmfCV6rvigVhs" },
    { name: "Harmony", id: "7t2ZyEiayA71HXxCzkln" },
    { name: "Heather Rey", id: "MnUw1cSnpiLoLhpd3Hqp" },
    { name: "Hope - upbeat and clear", id: "tnSpp4vdxKPjI9w0GnoV" },
    { name: "Jake - Confident & Engaging", id: "yDUXXKsu0jF5vdJnWAPU" },
    { name: "Jamal", id: "Ybqj6CIlqb6M85s9Bl4n" },
    { name: "Jaxon", id: "gReW7Niq8gxrfgxuUsmj" },
    { name: "Jessica Anne Bogart", id: "g6xIsTj2HwM6VR4iXFCw" },
    { name: "John", id: "EP3g1wv2wIp7Hc96Sf4l" },
    { name: "Johnny - Upbeat Professional", id: "JZ3e95uoTACVf6tXaaEi" },
    { name: "Josh Braun", id: "TbqP9kwNSb2NxaUNf8Jo" },
    { name: "Kevin", id: "O4RbJdGpWDGtbe9PybQ5" },
    { name: "Kimber K", id: "fQ74DTbwd8TiAJFxu9v8" },
    { name: "Louis Bloom", id: "DntmCwaJxxTEIxwC6WmP" },
    { name: "Luca - calm, soothing, steady", id: "4JVOFy4SLQs9my0OLhEw" },
    { name: "Matthew - Casual American Man", id: "IjnA9kwZJHJ20Fp7Vmy6" },
    { name: "Mia - Clear, Smooth, Professional", id: "rCuVrCHOUMY3OwyJBJym" },
    { name: "Mine", id: "CpFrrm3xLio4vWTEbo0m" },
    { name: "Miranda", id: "PoHUWWWMHFrA8z7Q88pu" },
    { name: "Miss Brittany Andrews", id: "fltzoUQ2F2VayM12sB6w" },
    { name: "Natasha valley girl", id: "g1gkVFi2jgj2rTKdNDq7" },
    { name: "Nevin", id: "Lq3QTLIHMhQILiCnYjTG" },
    { name: "New York Nick", id: "QH0iMHD2kQD6054yg01N" },
    { name: "Nia Davis- Black Female", id: "CBHdTdZwkV4jYoCyMV1B" },
    { name: "Nichalia Schwartz", id: "XfNU2rGpBa01ckF309OY" },
    { name: "Paul - (sped up)", id: "TC46yNhl5pQS6ekc0ZzW" },
    { name: "Piper", id: "DtsPFCrhbCbbJkwZsb3d" },
    { name: "Road Dawg", id: "gYr8yTP0q4RkX1HnzQfX" },
    { name: "Ryan Kurk", id: "rU18Fk3uSDhmg5Xh41o4" },
    { name: "Sara - Missouri resident", id: "a4SZwHT3FMKGrM6vbf60" },
    { name: "Sean", id: "8PfKWdrd6AySXM79vw0D" },
    { name: "Tanya", id: "Bwff1jnzl1s94AEcntUq" },
    { name: "The great conversationalist", id: "RNnkVeW25AwKYxZgnHBH" },
    { name: "Tiffany Kim - gritty yet articulate", id: "x9leqCOAXOcmC5jtkq65" },
    { name: "Tomas", id: "8sGzMkj2HZn6rYwGx6G0" },
    { name: "Tommy Tittlewooskie", id: "UuDE0Ki4TEAyPHmuPW9p" },
    { name: "Tyler Kurk", id: "raMcNf2S8wCmuaBcyI6E" },
    { name: "Vivie", id: "z7U1SjrEq4fDDDriOQEN" },
    { name: "Young Jamal", id: "6OzrBCQf8cjERkYgzSg8" },
    { name: "Zuri", id: "C3x1TEM7scV4p2AXJyrp" },
    

] as const
